// TR banka listesi (F1 seed). "Diğer" seçilince serbest metin girilir.
export const BANKS: string[] = [
  "Ziraat Bankası",
  "Türkiye İş Bankası",
  "Garanti BBVA",
  "Yapı Kredi",
  "Akbank",
  "Halkbank",
  "VakıfBank",
  "QNB",
  "DenizBank",
  "TEB",
  "Şekerbank",
  "ING",
  "HSBC",
  "Fibabanka",
  "Alternatif Bank",
  "Odeabank",
  "Burgan Bank",
  "Anadolubank",
  "ICBC Turkey",
  "Kuveyt Türk",
  "Albaraka Türk",
  "Türkiye Finans",
  "Ziraat Katılım",
  "Vakıf Katılım",
  "Emlak Katılım",
  "Enpara",
  "CEPTETEB",
  "Papara",
  "Tosla",
];

export const OTHER_BANK = "Diğer";
